export const UPLOAD_FOLLOWUPTITLE_REQUEST = "UPLOAD_FOLLOWUPTITLE_REQUEST"
export const UPLOAD_FOLLOWUPTITLE_SUCCESS = "UPLOAD_FOLLOWUPTITLE_SUCCESS"
export const UPLOAD_FOLLOWUPTITLE_FAILED = "UPLOAD_FOLLOWUPTITLE_FAILED"

export const UPDATE_FOLLOWUPTITLE_REQUEST = "UPDATE_FOLLOWUPTITLE_REQUEST"
export const UPDATE_FOLLOWUPTITLE_SUCCESS = "UPDATE_FOLLOWUPTITLE_SUCCESS"
export const UPDATE_FOLLOWUPTITLE_FAILED = "UPDATE_FOLLOWUPTITLE_FAILED"


export const GET_FOLLOWUPTITLE_REQUEST = "GET_FOLLOWUPTITLE_REQUEST"
export const GET_FOLLOWUPTITLE_SUCCESS = "GET_FOLLOWUPTITLE_SUCCESS"
export const GET_FOLLOWUPTITLE_FAILED = "GET_FOLLOWUPTITLE_FAILED"

export const CLEAR_ERRORS = "CLEAR_ERRORS"