export const UPLOAD_LOGO_REQUEST = "UPLOAD_LOGO_REQUEST"
export const UPLOAD_LOGO_SUCCESS = "UPLOAD_LOGO_SUCCESS"
export const UPLOAD_LOGO_FAILED = "UPLOAD_LOGO_FAILED"

export const UPDATE_LOGO_REQUEST = "UPDATE_LOGO_REQUEST"
export const UPDATE_LOGO_SUCCESS = "UPDATE_LOGO_SUCCESS"
export const UPDATE_LOGO_FAILED = "UPDATE_LOGO_FAILED"


export const GET_LOGO_REQUEST = "GET_LOGO_REQUEST"
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS"
export const GET_LOGO_FAILED = "GET_LOGO_FAILED"

export const CLEAR_ERRORS = "CLEAR_ERRORS"