export const UPLOAD_SOCIAL_REQUEST = "UPLOAD_SOCIAL_REQUEST"
export const UPLOAD_SOCIAL_SUCCESS = "UPLOAD_SOCIAL_SUCCESS"
export const UPLOAD_SOCIAL_FAILED = "UPLOAD_SOCIAL_FAILED"

export const UPDATE_SOCIAL_REQUEST = "UPDATE_SOCIAL_REQUEST"
export const UPDATE_SOCIAL_SUCCESS = "UPDATE_SOCIAL_SUCCESS"
export const UPDATE_SOCIAL_FAILED = "UPDATE_SOCIAL_FAILED"


export const GET_SOCIAL_REQUEST = "GET_SOCIAL_REQUEST"
export const GET_SOCIAL_SUCCESS = "GET_SOCIAL_SUCCESS"
export const GET_SOCIAL_FAILED = "GET_SOCIAL_FAILED"

export const CLEAR_ERRORS = "CLEAR_ERRORS"