export const UPLOAD_TITLE_REQUEST = "UPLOAD_TITLE_REQUEST"
export const UPLOAD_TITLE_SUCCESS = "UPLOAD_TITLE_SUCCESS"
export const UPLOAD_TITLE_FAILED = "UPLOAD_TITLE_FAILED"

export const UPDATE_TITLE_REQUEST = "UPDATE_TITLE_REQUEST"
export const UPDATE_TITLE_SUCCESS = "UPDATE_TITLE_SUCCESS"
export const UPDATE_TITLE_FAILED = "UPDATE_TITLE_FAILED"


export const GET_TITLE_REQUEST = "GET_TITLE_REQUEST"
export const GET_TITLE_SUCCESS = "GET_TITLE_SUCCESS"
export const GET_TITLE_FAILED = "GET_TITLE_FAILED"

export const CLEAR_ERRORS = "CLEAR_ERRORS"